@startuml 
title UseCase for Information system
left to right direction
skinparam packageStyle rect
actor User
actor Lector
actor Student
actor Google_Pay
rectangle Software {
  User -- (Authorization)
  User <|-- Lector
  
    Student <-- (Pay for the order)
    Student <-- (Сomplete the order)
    Lector --> (Pay for the order)
   (Сomplete the order) --> Lector
   (Pay by card) --> Google_Pay
   
   (Authorization) <. (Create the order) : <<include>>
   (Pay for the order) <.. (Authorization) : <<include>>
   (Сomplete the order) <.. (Authorization) : <<include>>
   (Pay for the order) <.. (Pay by card) : <<extend>>
   }
@enduml
